build: false

environment:
  matrix:
    - PYTHON: "C:/Python33"
    - PYTHON: "C:/Python34"
    - PYTHON: "C:/Python35"
    - PYTHON: "C:/Python36"

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

test_script:
  - "%PYTHON%/python.exe setup.py test"
